/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SideBarLayoutImport } from './routes/_sideBarLayout'
import { Route as ProjectSideBarLayoutImport } from './routes/_projectSideBarLayout'
import { Route as HelpPasswordIndexImport } from './routes/help/password/index'
import { Route as AuthSignInIndexImport } from './routes/auth/sign-in/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as SideBarLayoutVideoArchiveIndexImport } from './routes/_sideBarLayout/video-archive/index'
import { Route as SideBarLayoutMyProjectIndexImport } from './routes/_sideBarLayout/my-project/index'
import { Route as SideBarLayoutMyPageIndexImport } from './routes/_sideBarLayout/my-page/index'
import { Route as SideBarLayoutDashboardIndexImport } from './routes/_sideBarLayout/dashboard/index'
import { Route as AuthSignUpFinishIndexImport } from './routes/auth/sign-up/finish/index'
import { Route as AuthCallbackKakaoIndexImport } from './routes/auth/callback/kakao/index'
import { Route as AuthCallbackGoogleIndexImport } from './routes/auth/callback/google/index'
import { Route as ProjectSideBarLayoutProjectTemplateIndexImport } from './routes/_projectSideBarLayout/$project/template/index'
import { Route as ProjectSideBarLayoutProjectScriptIndexImport } from './routes/_projectSideBarLayout/$project/script/index'
import { Route as ProjectSideBarLayoutProjectBackgroundIndexImport } from './routes/_projectSideBarLayout/$project/background/index'
import { Route as ProjectSideBarLayoutProjectAvatarIndexImport } from './routes/_projectSideBarLayout/$project/avatar/index'
import { Route as ProjectSideBarLayoutProjectArticleIndexImport } from './routes/_projectSideBarLayout/$project/article/index'
import { Route as SideBarLayoutMyProjectComponentsProjectCardImport } from './routes/_sideBarLayout/my-project/_components/projectCard'
import { Route as SideBarLayoutMyProjectComponentsDropdownSelectImport } from './routes/_sideBarLayout/my-project/_components/dropdownSelect'
import { Route as SideBarLayoutDashboardComponentsMyProjectCardImport } from './routes/_sideBarLayout/dashboard/_components/myProjectCard'
import { Route as SideBarLayoutDashboardComponentsGuideImport } from './routes/_sideBarLayout/dashboard/_components/guide'
import { Route as SideBarLayoutDashboardComponentsChartImport } from './routes/_sideBarLayout/dashboard/_components/chart'

// Create/Update Routes

const SideBarLayoutRoute = SideBarLayoutImport.update({
  id: '/_sideBarLayout',
  getParentRoute: () => rootRoute,
} as any)

const ProjectSideBarLayoutRoute = ProjectSideBarLayoutImport.update({
  id: '/_projectSideBarLayout',
  getParentRoute: () => rootRoute,
} as any)

const HelpPasswordIndexRoute = HelpPasswordIndexImport.update({
  id: '/help/password/',
  path: '/help/password/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInIndexRoute = AuthSignInIndexImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const SideBarLayoutVideoArchiveIndexRoute =
  SideBarLayoutVideoArchiveIndexImport.update({
    id: '/video-archive/',
    path: '/video-archive/',
    getParentRoute: () => SideBarLayoutRoute,
  } as any)

const SideBarLayoutMyProjectIndexRoute =
  SideBarLayoutMyProjectIndexImport.update({
    id: '/my-project/',
    path: '/my-project/',
    getParentRoute: () => SideBarLayoutRoute,
  } as any)

const SideBarLayoutMyPageIndexRoute = SideBarLayoutMyPageIndexImport.update({
  id: '/my-page/',
  path: '/my-page/',
  getParentRoute: () => SideBarLayoutRoute,
} as any)

const SideBarLayoutDashboardIndexRoute =
  SideBarLayoutDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => SideBarLayoutRoute,
  } as any)

const AuthSignUpFinishIndexRoute = AuthSignUpFinishIndexImport.update({
  id: '/auth/sign-up/finish/',
  path: '/auth/sign-up/finish/',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackKakaoIndexRoute = AuthCallbackKakaoIndexImport.update({
  id: '/auth/callback/kakao/',
  path: '/auth/callback/kakao/',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackGoogleIndexRoute = AuthCallbackGoogleIndexImport.update({
  id: '/auth/callback/google/',
  path: '/auth/callback/google/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectSideBarLayoutProjectTemplateIndexRoute =
  ProjectSideBarLayoutProjectTemplateIndexImport.update({
    id: '/$project/template/',
    path: '/$project/template/',
    getParentRoute: () => ProjectSideBarLayoutRoute,
  } as any)

const ProjectSideBarLayoutProjectScriptIndexRoute =
  ProjectSideBarLayoutProjectScriptIndexImport.update({
    id: '/$project/script/',
    path: '/$project/script/',
    getParentRoute: () => ProjectSideBarLayoutRoute,
  } as any)

const ProjectSideBarLayoutProjectBackgroundIndexRoute =
  ProjectSideBarLayoutProjectBackgroundIndexImport.update({
    id: '/$project/background/',
    path: '/$project/background/',
    getParentRoute: () => ProjectSideBarLayoutRoute,
  } as any)

const ProjectSideBarLayoutProjectAvatarIndexRoute =
  ProjectSideBarLayoutProjectAvatarIndexImport.update({
    id: '/$project/avatar/',
    path: '/$project/avatar/',
    getParentRoute: () => ProjectSideBarLayoutRoute,
  } as any)

const ProjectSideBarLayoutProjectArticleIndexRoute =
  ProjectSideBarLayoutProjectArticleIndexImport.update({
    id: '/$project/article/',
    path: '/$project/article/',
    getParentRoute: () => ProjectSideBarLayoutRoute,
  } as any)

const SideBarLayoutMyProjectComponentsProjectCardRoute =
  SideBarLayoutMyProjectComponentsProjectCardImport.update({
    id: '/my-project/_components/projectCard',
    path: '/my-project/projectCard',
    getParentRoute: () => SideBarLayoutRoute,
  } as any)

const SideBarLayoutMyProjectComponentsDropdownSelectRoute =
  SideBarLayoutMyProjectComponentsDropdownSelectImport.update({
    id: '/my-project/_components/dropdownSelect',
    path: '/my-project/dropdownSelect',
    getParentRoute: () => SideBarLayoutRoute,
  } as any)

const SideBarLayoutDashboardComponentsMyProjectCardRoute =
  SideBarLayoutDashboardComponentsMyProjectCardImport.update({
    id: '/dashboard/_components/myProjectCard',
    path: '/dashboard/myProjectCard',
    getParentRoute: () => SideBarLayoutRoute,
  } as any)

const SideBarLayoutDashboardComponentsGuideRoute =
  SideBarLayoutDashboardComponentsGuideImport.update({
    id: '/dashboard/_components/guide',
    path: '/dashboard/guide',
    getParentRoute: () => SideBarLayoutRoute,
  } as any)

const SideBarLayoutDashboardComponentsChartRoute =
  SideBarLayoutDashboardComponentsChartImport.update({
    id: '/dashboard/_components/chart',
    path: '/dashboard/chart',
    getParentRoute: () => SideBarLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_projectSideBarLayout': {
      id: '/_projectSideBarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProjectSideBarLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_sideBarLayout': {
      id: '/_sideBarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SideBarLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_sideBarLayout/dashboard/': {
      id: '/_sideBarLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SideBarLayoutDashboardIndexImport
      parentRoute: typeof SideBarLayoutImport
    }
    '/_sideBarLayout/my-page/': {
      id: '/_sideBarLayout/my-page/'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof SideBarLayoutMyPageIndexImport
      parentRoute: typeof SideBarLayoutImport
    }
    '/_sideBarLayout/my-project/': {
      id: '/_sideBarLayout/my-project/'
      path: '/my-project'
      fullPath: '/my-project'
      preLoaderRoute: typeof SideBarLayoutMyProjectIndexImport
      parentRoute: typeof SideBarLayoutImport
    }
    '/_sideBarLayout/video-archive/': {
      id: '/_sideBarLayout/video-archive/'
      path: '/video-archive'
      fullPath: '/video-archive'
      preLoaderRoute: typeof SideBarLayoutVideoArchiveIndexImport
      parentRoute: typeof SideBarLayoutImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexImport
      parentRoute: typeof rootRoute
    }
    '/help/password/': {
      id: '/help/password/'
      path: '/help/password'
      fullPath: '/help/password'
      preLoaderRoute: typeof HelpPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/_sideBarLayout/dashboard/_components/chart': {
      id: '/_sideBarLayout/dashboard/_components/chart'
      path: '/dashboard/chart'
      fullPath: '/dashboard/chart'
      preLoaderRoute: typeof SideBarLayoutDashboardComponentsChartImport
      parentRoute: typeof SideBarLayoutImport
    }
    '/_sideBarLayout/dashboard/_components/guide': {
      id: '/_sideBarLayout/dashboard/_components/guide'
      path: '/dashboard/guide'
      fullPath: '/dashboard/guide'
      preLoaderRoute: typeof SideBarLayoutDashboardComponentsGuideImport
      parentRoute: typeof SideBarLayoutImport
    }
    '/_sideBarLayout/dashboard/_components/myProjectCard': {
      id: '/_sideBarLayout/dashboard/_components/myProjectCard'
      path: '/dashboard/myProjectCard'
      fullPath: '/dashboard/myProjectCard'
      preLoaderRoute: typeof SideBarLayoutDashboardComponentsMyProjectCardImport
      parentRoute: typeof SideBarLayoutImport
    }
    '/_sideBarLayout/my-project/_components/dropdownSelect': {
      id: '/_sideBarLayout/my-project/_components/dropdownSelect'
      path: '/my-project/dropdownSelect'
      fullPath: '/my-project/dropdownSelect'
      preLoaderRoute: typeof SideBarLayoutMyProjectComponentsDropdownSelectImport
      parentRoute: typeof SideBarLayoutImport
    }
    '/_sideBarLayout/my-project/_components/projectCard': {
      id: '/_sideBarLayout/my-project/_components/projectCard'
      path: '/my-project/projectCard'
      fullPath: '/my-project/projectCard'
      preLoaderRoute: typeof SideBarLayoutMyProjectComponentsProjectCardImport
      parentRoute: typeof SideBarLayoutImport
    }
    '/_projectSideBarLayout/$project/article/': {
      id: '/_projectSideBarLayout/$project/article/'
      path: '/$project/article'
      fullPath: '/$project/article'
      preLoaderRoute: typeof ProjectSideBarLayoutProjectArticleIndexImport
      parentRoute: typeof ProjectSideBarLayoutImport
    }
    '/_projectSideBarLayout/$project/avatar/': {
      id: '/_projectSideBarLayout/$project/avatar/'
      path: '/$project/avatar'
      fullPath: '/$project/avatar'
      preLoaderRoute: typeof ProjectSideBarLayoutProjectAvatarIndexImport
      parentRoute: typeof ProjectSideBarLayoutImport
    }
    '/_projectSideBarLayout/$project/background/': {
      id: '/_projectSideBarLayout/$project/background/'
      path: '/$project/background'
      fullPath: '/$project/background'
      preLoaderRoute: typeof ProjectSideBarLayoutProjectBackgroundIndexImport
      parentRoute: typeof ProjectSideBarLayoutImport
    }
    '/_projectSideBarLayout/$project/script/': {
      id: '/_projectSideBarLayout/$project/script/'
      path: '/$project/script'
      fullPath: '/$project/script'
      preLoaderRoute: typeof ProjectSideBarLayoutProjectScriptIndexImport
      parentRoute: typeof ProjectSideBarLayoutImport
    }
    '/_projectSideBarLayout/$project/template/': {
      id: '/_projectSideBarLayout/$project/template/'
      path: '/$project/template'
      fullPath: '/$project/template'
      preLoaderRoute: typeof ProjectSideBarLayoutProjectTemplateIndexImport
      parentRoute: typeof ProjectSideBarLayoutImport
    }
    '/auth/callback/google/': {
      id: '/auth/callback/google/'
      path: '/auth/callback/google'
      fullPath: '/auth/callback/google'
      preLoaderRoute: typeof AuthCallbackGoogleIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/callback/kakao/': {
      id: '/auth/callback/kakao/'
      path: '/auth/callback/kakao'
      fullPath: '/auth/callback/kakao'
      preLoaderRoute: typeof AuthCallbackKakaoIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up/finish/': {
      id: '/auth/sign-up/finish/'
      path: '/auth/sign-up/finish'
      fullPath: '/auth/sign-up/finish'
      preLoaderRoute: typeof AuthSignUpFinishIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ProjectSideBarLayoutRouteChildren {
  ProjectSideBarLayoutProjectArticleIndexRoute: typeof ProjectSideBarLayoutProjectArticleIndexRoute
  ProjectSideBarLayoutProjectAvatarIndexRoute: typeof ProjectSideBarLayoutProjectAvatarIndexRoute
  ProjectSideBarLayoutProjectBackgroundIndexRoute: typeof ProjectSideBarLayoutProjectBackgroundIndexRoute
  ProjectSideBarLayoutProjectScriptIndexRoute: typeof ProjectSideBarLayoutProjectScriptIndexRoute
  ProjectSideBarLayoutProjectTemplateIndexRoute: typeof ProjectSideBarLayoutProjectTemplateIndexRoute
}

const ProjectSideBarLayoutRouteChildren: ProjectSideBarLayoutRouteChildren = {
  ProjectSideBarLayoutProjectArticleIndexRoute:
    ProjectSideBarLayoutProjectArticleIndexRoute,
  ProjectSideBarLayoutProjectAvatarIndexRoute:
    ProjectSideBarLayoutProjectAvatarIndexRoute,
  ProjectSideBarLayoutProjectBackgroundIndexRoute:
    ProjectSideBarLayoutProjectBackgroundIndexRoute,
  ProjectSideBarLayoutProjectScriptIndexRoute:
    ProjectSideBarLayoutProjectScriptIndexRoute,
  ProjectSideBarLayoutProjectTemplateIndexRoute:
    ProjectSideBarLayoutProjectTemplateIndexRoute,
}

const ProjectSideBarLayoutRouteWithChildren =
  ProjectSideBarLayoutRoute._addFileChildren(ProjectSideBarLayoutRouteChildren)

interface SideBarLayoutRouteChildren {
  SideBarLayoutDashboardIndexRoute: typeof SideBarLayoutDashboardIndexRoute
  SideBarLayoutMyPageIndexRoute: typeof SideBarLayoutMyPageIndexRoute
  SideBarLayoutMyProjectIndexRoute: typeof SideBarLayoutMyProjectIndexRoute
  SideBarLayoutVideoArchiveIndexRoute: typeof SideBarLayoutVideoArchiveIndexRoute
  SideBarLayoutDashboardComponentsChartRoute: typeof SideBarLayoutDashboardComponentsChartRoute
  SideBarLayoutDashboardComponentsGuideRoute: typeof SideBarLayoutDashboardComponentsGuideRoute
  SideBarLayoutDashboardComponentsMyProjectCardRoute: typeof SideBarLayoutDashboardComponentsMyProjectCardRoute
  SideBarLayoutMyProjectComponentsDropdownSelectRoute: typeof SideBarLayoutMyProjectComponentsDropdownSelectRoute
  SideBarLayoutMyProjectComponentsProjectCardRoute: typeof SideBarLayoutMyProjectComponentsProjectCardRoute
}

const SideBarLayoutRouteChildren: SideBarLayoutRouteChildren = {
  SideBarLayoutDashboardIndexRoute: SideBarLayoutDashboardIndexRoute,
  SideBarLayoutMyPageIndexRoute: SideBarLayoutMyPageIndexRoute,
  SideBarLayoutMyProjectIndexRoute: SideBarLayoutMyProjectIndexRoute,
  SideBarLayoutVideoArchiveIndexRoute: SideBarLayoutVideoArchiveIndexRoute,
  SideBarLayoutDashboardComponentsChartRoute:
    SideBarLayoutDashboardComponentsChartRoute,
  SideBarLayoutDashboardComponentsGuideRoute:
    SideBarLayoutDashboardComponentsGuideRoute,
  SideBarLayoutDashboardComponentsMyProjectCardRoute:
    SideBarLayoutDashboardComponentsMyProjectCardRoute,
  SideBarLayoutMyProjectComponentsDropdownSelectRoute:
    SideBarLayoutMyProjectComponentsDropdownSelectRoute,
  SideBarLayoutMyProjectComponentsProjectCardRoute:
    SideBarLayoutMyProjectComponentsProjectCardRoute,
}

const SideBarLayoutRouteWithChildren = SideBarLayoutRoute._addFileChildren(
  SideBarLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof SideBarLayoutRouteWithChildren
  '/dashboard': typeof SideBarLayoutDashboardIndexRoute
  '/my-page': typeof SideBarLayoutMyPageIndexRoute
  '/my-project': typeof SideBarLayoutMyProjectIndexRoute
  '/video-archive': typeof SideBarLayoutVideoArchiveIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/help/password': typeof HelpPasswordIndexRoute
  '/dashboard/chart': typeof SideBarLayoutDashboardComponentsChartRoute
  '/dashboard/guide': typeof SideBarLayoutDashboardComponentsGuideRoute
  '/dashboard/myProjectCard': typeof SideBarLayoutDashboardComponentsMyProjectCardRoute
  '/my-project/dropdownSelect': typeof SideBarLayoutMyProjectComponentsDropdownSelectRoute
  '/my-project/projectCard': typeof SideBarLayoutMyProjectComponentsProjectCardRoute
  '/$project/article': typeof ProjectSideBarLayoutProjectArticleIndexRoute
  '/$project/avatar': typeof ProjectSideBarLayoutProjectAvatarIndexRoute
  '/$project/background': typeof ProjectSideBarLayoutProjectBackgroundIndexRoute
  '/$project/script': typeof ProjectSideBarLayoutProjectScriptIndexRoute
  '/$project/template': typeof ProjectSideBarLayoutProjectTemplateIndexRoute
  '/auth/callback/google': typeof AuthCallbackGoogleIndexRoute
  '/auth/callback/kakao': typeof AuthCallbackKakaoIndexRoute
  '/auth/sign-up/finish': typeof AuthSignUpFinishIndexRoute
}

export interface FileRoutesByTo {
  '': typeof SideBarLayoutRouteWithChildren
  '/dashboard': typeof SideBarLayoutDashboardIndexRoute
  '/my-page': typeof SideBarLayoutMyPageIndexRoute
  '/my-project': typeof SideBarLayoutMyProjectIndexRoute
  '/video-archive': typeof SideBarLayoutVideoArchiveIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/help/password': typeof HelpPasswordIndexRoute
  '/dashboard/chart': typeof SideBarLayoutDashboardComponentsChartRoute
  '/dashboard/guide': typeof SideBarLayoutDashboardComponentsGuideRoute
  '/dashboard/myProjectCard': typeof SideBarLayoutDashboardComponentsMyProjectCardRoute
  '/my-project/dropdownSelect': typeof SideBarLayoutMyProjectComponentsDropdownSelectRoute
  '/my-project/projectCard': typeof SideBarLayoutMyProjectComponentsProjectCardRoute
  '/$project/article': typeof ProjectSideBarLayoutProjectArticleIndexRoute
  '/$project/avatar': typeof ProjectSideBarLayoutProjectAvatarIndexRoute
  '/$project/background': typeof ProjectSideBarLayoutProjectBackgroundIndexRoute
  '/$project/script': typeof ProjectSideBarLayoutProjectScriptIndexRoute
  '/$project/template': typeof ProjectSideBarLayoutProjectTemplateIndexRoute
  '/auth/callback/google': typeof AuthCallbackGoogleIndexRoute
  '/auth/callback/kakao': typeof AuthCallbackKakaoIndexRoute
  '/auth/sign-up/finish': typeof AuthSignUpFinishIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_projectSideBarLayout': typeof ProjectSideBarLayoutRouteWithChildren
  '/_sideBarLayout': typeof SideBarLayoutRouteWithChildren
  '/_sideBarLayout/dashboard/': typeof SideBarLayoutDashboardIndexRoute
  '/_sideBarLayout/my-page/': typeof SideBarLayoutMyPageIndexRoute
  '/_sideBarLayout/my-project/': typeof SideBarLayoutMyProjectIndexRoute
  '/_sideBarLayout/video-archive/': typeof SideBarLayoutVideoArchiveIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/help/password/': typeof HelpPasswordIndexRoute
  '/_sideBarLayout/dashboard/_components/chart': typeof SideBarLayoutDashboardComponentsChartRoute
  '/_sideBarLayout/dashboard/_components/guide': typeof SideBarLayoutDashboardComponentsGuideRoute
  '/_sideBarLayout/dashboard/_components/myProjectCard': typeof SideBarLayoutDashboardComponentsMyProjectCardRoute
  '/_sideBarLayout/my-project/_components/dropdownSelect': typeof SideBarLayoutMyProjectComponentsDropdownSelectRoute
  '/_sideBarLayout/my-project/_components/projectCard': typeof SideBarLayoutMyProjectComponentsProjectCardRoute
  '/_projectSideBarLayout/$project/article/': typeof ProjectSideBarLayoutProjectArticleIndexRoute
  '/_projectSideBarLayout/$project/avatar/': typeof ProjectSideBarLayoutProjectAvatarIndexRoute
  '/_projectSideBarLayout/$project/background/': typeof ProjectSideBarLayoutProjectBackgroundIndexRoute
  '/_projectSideBarLayout/$project/script/': typeof ProjectSideBarLayoutProjectScriptIndexRoute
  '/_projectSideBarLayout/$project/template/': typeof ProjectSideBarLayoutProjectTemplateIndexRoute
  '/auth/callback/google/': typeof AuthCallbackGoogleIndexRoute
  '/auth/callback/kakao/': typeof AuthCallbackKakaoIndexRoute
  '/auth/sign-up/finish/': typeof AuthSignUpFinishIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/my-page'
    | '/my-project'
    | '/video-archive'
    | '/auth/login'
    | '/auth/sign-in'
    | '/help/password'
    | '/dashboard/chart'
    | '/dashboard/guide'
    | '/dashboard/myProjectCard'
    | '/my-project/dropdownSelect'
    | '/my-project/projectCard'
    | '/$project/article'
    | '/$project/avatar'
    | '/$project/background'
    | '/$project/script'
    | '/$project/template'
    | '/auth/callback/google'
    | '/auth/callback/kakao'
    | '/auth/sign-up/finish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/dashboard'
    | '/my-page'
    | '/my-project'
    | '/video-archive'
    | '/auth/login'
    | '/auth/sign-in'
    | '/help/password'
    | '/dashboard/chart'
    | '/dashboard/guide'
    | '/dashboard/myProjectCard'
    | '/my-project/dropdownSelect'
    | '/my-project/projectCard'
    | '/$project/article'
    | '/$project/avatar'
    | '/$project/background'
    | '/$project/script'
    | '/$project/template'
    | '/auth/callback/google'
    | '/auth/callback/kakao'
    | '/auth/sign-up/finish'
  id:
    | '__root__'
    | '/_projectSideBarLayout'
    | '/_sideBarLayout'
    | '/_sideBarLayout/dashboard/'
    | '/_sideBarLayout/my-page/'
    | '/_sideBarLayout/my-project/'
    | '/_sideBarLayout/video-archive/'
    | '/auth/login/'
    | '/auth/sign-in/'
    | '/help/password/'
    | '/_sideBarLayout/dashboard/_components/chart'
    | '/_sideBarLayout/dashboard/_components/guide'
    | '/_sideBarLayout/dashboard/_components/myProjectCard'
    | '/_sideBarLayout/my-project/_components/dropdownSelect'
    | '/_sideBarLayout/my-project/_components/projectCard'
    | '/_projectSideBarLayout/$project/article/'
    | '/_projectSideBarLayout/$project/avatar/'
    | '/_projectSideBarLayout/$project/background/'
    | '/_projectSideBarLayout/$project/script/'
    | '/_projectSideBarLayout/$project/template/'
    | '/auth/callback/google/'
    | '/auth/callback/kakao/'
    | '/auth/sign-up/finish/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProjectSideBarLayoutRoute: typeof ProjectSideBarLayoutRouteWithChildren
  SideBarLayoutRoute: typeof SideBarLayoutRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  HelpPasswordIndexRoute: typeof HelpPasswordIndexRoute
  AuthCallbackGoogleIndexRoute: typeof AuthCallbackGoogleIndexRoute
  AuthCallbackKakaoIndexRoute: typeof AuthCallbackKakaoIndexRoute
  AuthSignUpFinishIndexRoute: typeof AuthSignUpFinishIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProjectSideBarLayoutRoute: ProjectSideBarLayoutRouteWithChildren,
  SideBarLayoutRoute: SideBarLayoutRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  HelpPasswordIndexRoute: HelpPasswordIndexRoute,
  AuthCallbackGoogleIndexRoute: AuthCallbackGoogleIndexRoute,
  AuthCallbackKakaoIndexRoute: AuthCallbackKakaoIndexRoute,
  AuthSignUpFinishIndexRoute: AuthSignUpFinishIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_projectSideBarLayout",
        "/_sideBarLayout",
        "/auth/login/",
        "/auth/sign-in/",
        "/help/password/",
        "/auth/callback/google/",
        "/auth/callback/kakao/",
        "/auth/sign-up/finish/"
      ]
    },
    "/_projectSideBarLayout": {
      "filePath": "_projectSideBarLayout.tsx",
      "children": [
        "/_projectSideBarLayout/$project/article/",
        "/_projectSideBarLayout/$project/avatar/",
        "/_projectSideBarLayout/$project/background/",
        "/_projectSideBarLayout/$project/script/",
        "/_projectSideBarLayout/$project/template/"
      ]
    },
    "/_sideBarLayout": {
      "filePath": "_sideBarLayout.tsx",
      "children": [
        "/_sideBarLayout/dashboard/",
        "/_sideBarLayout/my-page/",
        "/_sideBarLayout/my-project/",
        "/_sideBarLayout/video-archive/",
        "/_sideBarLayout/dashboard/_components/chart",
        "/_sideBarLayout/dashboard/_components/guide",
        "/_sideBarLayout/dashboard/_components/myProjectCard",
        "/_sideBarLayout/my-project/_components/dropdownSelect",
        "/_sideBarLayout/my-project/_components/projectCard"
      ]
    },
    "/_sideBarLayout/dashboard/": {
      "filePath": "_sideBarLayout/dashboard/index.tsx",
      "parent": "/_sideBarLayout"
    },
    "/_sideBarLayout/my-page/": {
      "filePath": "_sideBarLayout/my-page/index.tsx",
      "parent": "/_sideBarLayout"
    },
    "/_sideBarLayout/my-project/": {
      "filePath": "_sideBarLayout/my-project/index.tsx",
      "parent": "/_sideBarLayout"
    },
    "/_sideBarLayout/video-archive/": {
      "filePath": "_sideBarLayout/video-archive/index.tsx",
      "parent": "/_sideBarLayout"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/sign-in/": {
      "filePath": "auth/sign-in/index.tsx"
    },
    "/help/password/": {
      "filePath": "help/password/index.tsx"
    },
    "/_sideBarLayout/dashboard/_components/chart": {
      "filePath": "_sideBarLayout/dashboard/_components/chart.tsx",
      "parent": "/_sideBarLayout"
    },
    "/_sideBarLayout/dashboard/_components/guide": {
      "filePath": "_sideBarLayout/dashboard/_components/guide.tsx",
      "parent": "/_sideBarLayout"
    },
    "/_sideBarLayout/dashboard/_components/myProjectCard": {
      "filePath": "_sideBarLayout/dashboard/_components/myProjectCard.tsx",
      "parent": "/_sideBarLayout"
    },
    "/_sideBarLayout/my-project/_components/dropdownSelect": {
      "filePath": "_sideBarLayout/my-project/_components/dropdownSelect.tsx",
      "parent": "/_sideBarLayout"
    },
    "/_sideBarLayout/my-project/_components/projectCard": {
      "filePath": "_sideBarLayout/my-project/_components/projectCard.tsx",
      "parent": "/_sideBarLayout"
    },
    "/_projectSideBarLayout/$project/article/": {
      "filePath": "_projectSideBarLayout/$project/article/index.tsx",
      "parent": "/_projectSideBarLayout"
    },
    "/_projectSideBarLayout/$project/avatar/": {
      "filePath": "_projectSideBarLayout/$project/avatar/index.tsx",
      "parent": "/_projectSideBarLayout"
    },
    "/_projectSideBarLayout/$project/background/": {
      "filePath": "_projectSideBarLayout/$project/background/index.tsx",
      "parent": "/_projectSideBarLayout"
    },
    "/_projectSideBarLayout/$project/script/": {
      "filePath": "_projectSideBarLayout/$project/script/index.tsx",
      "parent": "/_projectSideBarLayout"
    },
    "/_projectSideBarLayout/$project/template/": {
      "filePath": "_projectSideBarLayout/$project/template/index.tsx",
      "parent": "/_projectSideBarLayout"
    },
    "/auth/callback/google/": {
      "filePath": "auth/callback/google/index.tsx"
    },
    "/auth/callback/kakao/": {
      "filePath": "auth/callback/kakao/index.tsx"
    },
    "/auth/sign-up/finish/": {
      "filePath": "auth/sign-up/finish/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
